$('#newProcessTabs-1').on('click', function() {
    $(this).addClass('new-process__block-tabs-active')
    $('#newProcessTabs-2').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-3').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-4').removeClass('new-process__block-tabs-active')
    $('#newProcessTabsList-1').removeClass('display-n')
    $('#newProcessTabsList-2').addClass('display-n')
    $('#newProcessTabsList-3').addClass('display-n')
    $('#newProcessTabsList-4').addClass('display-n')
})
$('#newProcessTabs-2').on('click', function() {
    $(this).addClass('new-process__block-tabs-active')
    $('#newProcessTabs-1').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-3').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-4').removeClass('new-process__block-tabs-active')
    $('#newProcessTabsList-2').removeClass('display-n')
    $('#newProcessTabsList-1').addClass('display-n')
    $('#newProcessTabsList-3').addClass('display-n')
    $('#newProcessTabsList-4').addClass('display-n')
})
$('#newProcessTabs-3').on('click', function() {
    $(this).addClass('new-process__block-tabs-active')
    $('#newProcessTabs-1').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-2').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-4').removeClass('new-process__block-tabs-active')
    $('#newProcessTabsList-3').removeClass('display-n')
    $('#newProcessTabsList-1').addClass('display-n')
    $('#newProcessTabsList-2').addClass('display-n')
    $('#newProcessTabsList-4').addClass('display-n')
})
$('#newProcessTabs-4').on('click', function() {
    $(this).addClass('new-process__block-tabs-active')
    $('#newProcessTabs-1').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-3').removeClass('new-process__block-tabs-active')
    $('#newProcessTabs-2').removeClass('new-process__block-tabs-active')
    $('#newProcessTabsList-4').removeClass('display-n')
    $('#newProcessTabsList-1').addClass('display-n')
    $('#newProcessTabsList-3').addClass('display-n')
    $('#newProcessTabsList-2').addClass('display-n')
})
